<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>


<?= $this->partial('partials/errores') ?>
<div class="p-5 mb-4 bg-light rounded-3">
    <h1><?= 'Actividad 3: Práctica de Tecnologías Emergentes'; ?>
    </h1>

    <div class="alert alert-info border-dark">
        <p>Información de servicios api/rest obtenida de:</p>
        <ul>
            <li><a href="https://sedeaplicaciones.minetur.gob.es/ServiciosRestCarburantes/PreciosCarburantes/help"
                   target="_blank">Catálogo
                    de Servicios Rest Ministerio de Industria y Turismo</a></li>
            <li><a href="https://datos.gob.es/es/catalogo/e05068001-precio-de-carburantes-en-las-gasolineras-espanolas"
                   target="_blank">Información
                    de Servicios web "Catálogo de carburantes en las gasolineras españolas"</a></li>
            <li><a href="https://geoportalgasolineras.es/geoportal-instalaciones/Inicio" target="_blank">Geoportal de
                    hidrocarburos
                </a></li>
        </ul>
    </div>

    <ul class="nav nav-tabs">
        <li class="nav-item">
            <button class="nav-link <?php if ($peticion == -1) echo 'active'; ?>" data-toggle="tab" id="geolocation-tab"
                    data-target="#geolocation-tab"
                    href="#geolocation-tab" type="button" role="tab" aria-controls="geolocation-tab"
                    aria-selected="true">
                Geolocation
            </button>
        </li>

        <li class="nav-item">
            <button class="nav-link" <?php if (in_array($peticion, [4, 5, 6])) echo 'active'; ?> data-toggle="tab"
                    id="peticiones-tab" data-target="#peticiones-tab"
                    href="#peticiones-tab" type="button" role="tab" aria-controls="peticiones-tab"
                    aria-selected="true">Peticiones (parte 1)
            </button>
        </li>

        <li class="nav-item">
            <button class="nav-link" <?php if (in_array($peticion, [0, 1, 2, 3])) echo 'active'; ?> data-toggle="tab"
                    id="gestion-tab" data-target="#gestion-tab"
                    href="#gestion-tab" type="button" role="tab" aria-controls="gestion-tab"
                    aria-selected="true">Gestión datos portal (parte 2)
            </button>
        </li>
    </ul>


    <div class="tab-content">

        <!--geolocation-->
        <?= $this->partial('partials/geolocation', ['peticion' => $peticion, 'location' => $locationData]) ?>

        <!--peticiones parte 1: valencia, aranjuez etc (peticiones en array urls códigos 4-5-6-->
        <?= $this->partial('partials/parte1', ['peticion' => $peticion, 'urls' => $urls, 'data' => $data]); ?>

        <!--peticiones parte 2:  (peticiones en array urls códigos 0-1-2-3-->
        <?= $this->partial('partials/parte2',
            ['peticion' => $peticion,
                'urls' => $urls, 'data' => $data,
                'comunidades' => $comunidades,
                'provincias' => $provincias,
                'cod_comunidad' => $cod_comunidad,
                'cod_municipio' => $cod_municipio,
                'fecha' => $id_fecha
            ]
        ); ?>


        <!-- tabla genérica-->
        <?php if (is_array($data) && !empty($data)) { ?>
            <?php foreach (array_keys($data) as $key) {
                if (!is_array($data[$key])) { ?>
                    <ul>
                        <li><?= $key . ': ' . $data[$key]; ?></li>
                    </ul>
                <?php } else { ?>
                    <table class="table table-striped table-bordered table-hover" id="table_extensible"
                    style="width: 100%">
                    <thead>
                    <ul>
                        <li><?= $key; ?>:</li>
                    </ul>
                    <tr>
                        <?php
                        $i = [];
                        foreach ($data[$key] as $array_precios_municipios) {
                            foreach ($array_precios_municipios as $key2 => $value2) {
                                if (!in_array($key2, $i)) { ?>
                                    <th scope="col"><?= $key2; ?></th>
                                    <?php array_push($i, strval($key2));
                                }
                            }
                        }
                        ?>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    $i2 = [];
                    foreach ($data[$key] as $array2) {
                        ?>
                        <tr>
                            <?php foreach ($array2 as $key3 => $value3) { ?>
                                <?php // if (!in_array($key3, $i2)) { ?>
                                <th scope="col"><?= $value3; ?></th>
                                <?php //array_push($i, strval($key2));
                            } ?>
                        </tr>
                    <?php }
                } ?>
                </tbody>
                </table>
            <?php }
        } ?>

    </div>
</div>


<!-- Formulario"resetear" -->
<form id="resetear" name="resetear" action="" method="post">
    <input type="hidden" id="resetear_peticion" name="peticion" value="-1">
</form>



