<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Laminas\Session\Container;
use Tfe\Util\Constantes;

$sesion = new Container (Constantes::NOMBRE_SESION);
?>


<?= $this->doctype() ?>
<html lang="es" class="h-100">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('UNIR Tecnologías Emergentes')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo-unir-default.png'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/responsive.datatables.css'))
        ->prependStylesheet($this->basePath('css/datatables.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.1/font/bootstrap-icons.css')
    ?>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300&family=Roboto:wght@300&display=swap"
          rel="stylesheet">
    <!-- Incluir CSS de Flatpickr -->
    <link href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css" rel="stylesheet">


</head>
<body class="d-flex flex-column h-100">

<nav class="navbar fixed-top navbar-expand-lg flex-column flex-lg-row
 <?php if (!$sesion->offsetGet(Constantes::SESION_ESTUDIANTE)) echo 'navbar-default'; else echo 'navbar-dark' ?>">

    <div class="container-fluid justify-content-between">

        <span class="fix_navbar"></span>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <?php if ($sesion->offsetExists(Constantes::SESION_ESTUDIANTE) && $sesion->offsetExists(Constantes::SESION_USUARIO)) { ?>
            <?= $this->partial('partials/menu-estudiante') ?>
        <?php } else if ($sesion->offsetExists(Constantes::SESION_DOCENTE) && $sesion->offsetExists(Constantes::SESION_USUARIO_DOCENTE)) { ?>
            <?= $this->partial('partials/menu-docente') ?>
        <?php } ?>



        <?php if ($sesion->offsetGet(Constantes::SESION_DOCENTE) && !$sesion->offsetExists(Constantes::SESION_USUARIO_DOCENTE)) { ?>
            <span class="navbar-text">
                    <a class="nav-link"
                       href="<?= $this->url('login') ?>">
                       UNIR <i class="bi bi-person"></i>
                    </a>
            </span>
        <?php } ?>
        <?php if (1 || $sesion->offsetGet(Constantes::SESION_ESTUDIANTE) && !$sesion->offsetExists(Constantes::SESION_USUARIO)) { ?>
            <span class="navbar-text">
                    <a class="nav-link"
                       href=".">
                   UNIR <i class="bi bi-book"></i>
                    </a>
            </span>
        <?php } ?>

    </div>
</nav>

<main class="flex-shrink-0">
    <div class="container">
        <?= $this->content ?>
        <hr>
    </div>
</main>

<footer class="footer mt-auto py-3
<?php if (!$sesion->offsetGet(Constantes::SESION_ESTUDIANTE)) echo 'bck-primary'; else echo 'bck-primary-ligth' ?>
">
    <div class="container">
        <p class="<?php if (!$sesion->offsetGet(Constantes::SESION_ESTUDIANTE)) echo 'text-white' ?>">
            &copy; <?= date('Y') ?>
            <a target="_blank" href="www.unir.es">UNIR </a> Tecnologías emergentes
        </p>
    </div>
</footer>
<?php //echo $this->headScript(); ?>
<!-- Scripts -->
<!-- Enable tooltips and drpopdowns for bootstrap min error !-->
<script
        src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"
></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
    // Inicializar Flatpickr con opciones en español, rango de años, y formato de fecha
    flatpickr("#fecha", {
        locale: "es",  // Español
        dateFormat: "d-m-Y",  // Formato: dd-mm-aaaa
        minDate: "2020-01-01",  // Fecha mínima: 2020
        maxDate: new Date(),  // Fecha máxima: hoy
        yearRange: [2020, 2025],  // Rango de años entre 2020 y 2025
        disableMobile: true, // Desactivar versión móvil (opcional)
    });
</script>
<?= $this->inlineScript()
    ->prependFile($this->basePath('js/jquery.validate.js'))
    ->prependFile($this->basePath('js/form-validation.js'))
    ->prependFile($this->basePath('js/datatables.js'))
    ->prependFile($this->basePath('js/table-datatables-responsive.js'))
    ->prependFile($this->basePath('js/functions.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>

<script>
    jQuery(document).ready(function () {
        TableDatatablesResponsive.init();
        FormValidation.init();
    });
</script>
</body>
</html>
